#!/bin/sh
ssh -t ubuntu@3.34.215.88 <<EOF
    cd ~/JenkinsNodeJS
    git pull 
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.2.0
    npm install
    npm start
    exit
EOF
